### ISSUE TITLE
如何修改图片默认保存路径

### ISSUE THREAD

**Issue by scavin** [yAnXImIN/weiboPicDownloader#1]
RT

是修改 WeiboDownloader.java 33 行么？

**Comment by jnduan** [comment]
建议作者搞个配置文件来配置存储路径，否则改完还得重新编译啥的，难道一堆小白。

另外，IDE相关的东西，可以gitignore一下。。。

**Comment by scavin** [comment]
我在 Mac 下测试后，图片是被保存在 ./bin/E/\img\ 里面的（这么个奇葩名

http://www.appinn.com/weibo-pic-downloader-java/

**Comment by NV3S** [comment]
没装环境，直接
`subst E: D:\img
`完后 
`subst /D E:`

**Comment by touzi** [comment]
@scavin 代码的确是那个地方, 但改完之后需要从新编译.

**Comment by touzi** [comment]
我从新编译的, 存放路径默认在 C 盘根目录. 
windows 10 如果没有 E 盘直接报错. 

https://github.com/touzi/File/blob/master/wb.jar

**Comment by yAnXImIN** [comment]
楼上各位的需求已经收到. 随手写的, 代码不太规范啊~

**Comment by yAnXImIN** [comment]
已修改
