### ISSUE TITLE
图片后缀不一定都是JPG啊

### ISSUE THREAD

**Issue by nondanee** [yAnXImIN/weiboPicDownloader#3]
有没有png我不知道，但是肯定还有gif啊。
```FileUtils.byte2File(imgbytes,IMG_LOCATION + containerId.substring(6), i+1+".jpg");```
后缀名还是要从webUrl获得一下的嗯
我不会java所以不能PR帮你改了~~~

我用python移植了这个repo
https://github.com/nondanee/weiboPicDownloader
可不可以在你这里挂一下啊（逃

**Comment by yAnXImIN** [comment]
收到，下个版本会改一下

**Comment by nondanee** [comment]
嗯嗯好
